// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/predictive-search": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/llms.txt": {
    params: {};
  };
  "/:locale?": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/blogs/:blogHandle/:articleHandle": {
    params: {
      "locale"?: string;
      "blogHandle": string;
      "articleHandle": string;
    };
  };
  "/:locale?/sitemap/:type/:page.xml": {
    params: {
      "locale"?: string;
      "type": string;
      "page": string;
    };
  };
  "/:locale?/blogs/:blogHandle": {
    params: {
      "locale"?: string;
      "blogHandle": string;
    };
  };
  "/:locale?/collections/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/collections": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/policies/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/products/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/collections/all": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/policies": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/products": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/discount/:code": {
    params: {
      "locale"?: string;
      "code": string;
    };
  };
  "/:locale?/pages/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/sitemap.xml": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/blogs": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/search": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/cart": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/cart/:lines": {
    params: {
      "locale"?: string;
      "lines": string;
    };
  };
  "/:locale?/*": {
    params: {
      "locale"?: string;
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/predictive-search" | "/robots.txt" | "/llms.txt" | "/:locale?" | "/:locale?/blogs/:blogHandle/:articleHandle" | "/:locale?/sitemap/:type/:page.xml" | "/:locale?/blogs/:blogHandle" | "/:locale?/collections/:handle" | "/:locale?/collections" | "/:locale?/policies/:handle" | "/:locale?/products/:handle" | "/:locale?/collections/all" | "/:locale?/policies" | "/:locale?/products" | "/:locale?/discount/:code" | "/:locale?/pages/:handle" | "/:locale?/sitemap.xml" | "/:locale?/blogs" | "/:locale?/search" | "/:locale?/cart" | "/:locale?/cart/:lines" | "/:locale?/*";
  };
  "routes/api.predictive-search.tsx": {
    id: "routes/api.predictive-search";
    page: "/api/predictive-search";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/[llms.txt].tsx": {
    id: "routes/[llms.txt]";
    page: "/llms.txt";
  };
  "routes/($locale).tsx": {
    id: "routes/($locale)";
    page: "/:locale?" | "/:locale?/blogs/:blogHandle/:articleHandle" | "/:locale?/sitemap/:type/:page.xml" | "/:locale?/blogs/:blogHandle" | "/:locale?/collections/:handle" | "/:locale?/collections" | "/:locale?/policies/:handle" | "/:locale?/products/:handle" | "/:locale?/collections/all" | "/:locale?/policies" | "/:locale?/products" | "/:locale?/discount/:code" | "/:locale?/pages/:handle" | "/:locale?/sitemap.xml" | "/:locale?/blogs" | "/:locale?/search" | "/:locale?/cart" | "/:locale?/cart/:lines" | "/:locale?/*";
  };
  "routes/($locale).blogs.$blogHandle.$articleHandle.tsx": {
    id: "routes/($locale).blogs.$blogHandle.$articleHandle";
    page: "/:locale?/blogs/:blogHandle/:articleHandle";
  };
  "routes/($locale).sitemap.$type.$page[.xml].tsx": {
    id: "routes/($locale).sitemap.$type.$page[.xml]";
    page: "/:locale?/sitemap/:type/:page.xml";
  };
  "routes/($locale).blogs.$blogHandle._index.tsx": {
    id: "routes/($locale).blogs.$blogHandle._index";
    page: "/:locale?/blogs/:blogHandle";
  };
  "routes/($locale).collections.$handle.tsx": {
    id: "routes/($locale).collections.$handle";
    page: "/:locale?/collections/:handle";
  };
  "routes/($locale).collections._index.tsx": {
    id: "routes/($locale).collections._index";
    page: "/:locale?/collections";
  };
  "routes/($locale).policies.$handle.tsx": {
    id: "routes/($locale).policies.$handle";
    page: "/:locale?/policies/:handle";
  };
  "routes/($locale).products.$handle.tsx": {
    id: "routes/($locale).products.$handle";
    page: "/:locale?/products/:handle";
  };
  "routes/($locale).collections.all.tsx": {
    id: "routes/($locale).collections.all";
    page: "/:locale?/collections/all";
  };
  "routes/($locale).policies._index.tsx": {
    id: "routes/($locale).policies._index";
    page: "/:locale?/policies";
  };
  "routes/($locale).products._index.tsx": {
    id: "routes/($locale).products._index";
    page: "/:locale?/products";
  };
  "routes/($locale).discount.$code.tsx": {
    id: "routes/($locale).discount.$code";
    page: "/:locale?/discount/:code";
  };
  "routes/($locale).pages.$handle.tsx": {
    id: "routes/($locale).pages.$handle";
    page: "/:locale?/pages/:handle";
  };
  "routes/($locale).[sitemap.xml].tsx": {
    id: "routes/($locale).[sitemap.xml]";
    page: "/:locale?/sitemap.xml";
  };
  "routes/($locale).blogs._index.tsx": {
    id: "routes/($locale).blogs._index";
    page: "/:locale?/blogs";
  };
  "routes/($locale).search.tsx": {
    id: "routes/($locale).search";
    page: "/:locale?/search";
  };
  "routes/($locale)._index.tsx": {
    id: "routes/($locale)._index";
    page: "/:locale?";
  };
  "routes/($locale).cart.tsx": {
    id: "routes/($locale).cart";
    page: "/:locale?/cart" | "/:locale?/cart/:lines";
  };
  "routes/($locale).cart.$lines.tsx": {
    id: "routes/($locale).cart.$lines";
    page: "/:locale?/cart/:lines";
  };
  "routes/($locale).$.tsx": {
    id: "routes/($locale).$";
    page: "/:locale?/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.predictive-search": typeof import("./app/routes/api.predictive-search.tsx");
  "routes/[robots.txt]": typeof import("./app/routes/[robots.txt].tsx");
  "routes/[llms.txt]": typeof import("./app/routes/[llms.txt].tsx");
  "routes/($locale)": typeof import("./app/routes/($locale).tsx");
  "routes/($locale).blogs.$blogHandle.$articleHandle": typeof import("./app/routes/($locale).blogs.$blogHandle.$articleHandle.tsx");
  "routes/($locale).sitemap.$type.$page[.xml]": typeof import("./app/routes/($locale).sitemap.$type.$page[.xml].tsx");
  "routes/($locale).blogs.$blogHandle._index": typeof import("./app/routes/($locale).blogs.$blogHandle._index.tsx");
  "routes/($locale).collections.$handle": typeof import("./app/routes/($locale).collections.$handle.tsx");
  "routes/($locale).collections._index": typeof import("./app/routes/($locale).collections._index.tsx");
  "routes/($locale).policies.$handle": typeof import("./app/routes/($locale).policies.$handle.tsx");
  "routes/($locale).products.$handle": typeof import("./app/routes/($locale).products.$handle.tsx");
  "routes/($locale).collections.all": typeof import("./app/routes/($locale).collections.all.tsx");
  "routes/($locale).policies._index": typeof import("./app/routes/($locale).policies._index.tsx");
  "routes/($locale).products._index": typeof import("./app/routes/($locale).products._index.tsx");
  "routes/($locale).discount.$code": typeof import("./app/routes/($locale).discount.$code.tsx");
  "routes/($locale).pages.$handle": typeof import("./app/routes/($locale).pages.$handle.tsx");
  "routes/($locale).[sitemap.xml]": typeof import("./app/routes/($locale).[sitemap.xml].tsx");
  "routes/($locale).blogs._index": typeof import("./app/routes/($locale).blogs._index.tsx");
  "routes/($locale).search": typeof import("./app/routes/($locale).search.tsx");
  "routes/($locale)._index": typeof import("./app/routes/($locale)._index.tsx");
  "routes/($locale).cart": typeof import("./app/routes/($locale).cart.tsx");
  "routes/($locale).cart.$lines": typeof import("./app/routes/($locale).cart.$lines.tsx");
  "routes/($locale).$": typeof import("./app/routes/($locale).$.tsx");
};